name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-3c1izth856nemi5l.cn-beijing.personal.cr.aliyuncs.com
        username: 15202821880
        password: Qq123456@~
        logout: false
        
    - name: Use1 Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://rancher/shell:v0.1.18 docker://crpi-3c1izth856nemi5l.cn-beijing.personal.cr.aliyuncs.com/cloudtest123/rancher-shell:v0.1.18
